### ISSUE TITLE
Enable use of D keywords as identifiers when interfacing to C/C++

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#19093]
### CC List

* Mathias LANG (@Geod24)
* Tim

### Description

````markdown
Consider:

    extern (C) int* with();

where delegate is a C function name. This, of course, fails because 'with' is a D keyword. A solution is:

    extern (C) int* with_();

and have the C/C++ name mangler remove any trailing _ from identifiers.

The prefix version, _with, has problems because it would be impossible to have a C identifier named '_traits' or '_gshared'.
````

**Comment by dlangBugzillaToGithub** [comment]
#### dfj1esp02 commented on 2016-01-22T08:16:31Z



````markdown
Another option:
extern (C++) int __symbol__with();
And let C++ mangler recognize and remove the __symbol__ prefix.

Choose your naming convention:
alias with_ = __symbol__with;
alias _with = __symbol__with;
alias _with_ = __symbol__with;
alias With = __symbol__with;
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2017-07-08T01:46:14Z



````markdown
In this particular case, the easiest workaround is to use pragma(mangle), right?

I understand that this is more useful for C++ functions, whose mangling is non-trivial.
````

**Comment by dlangBugzillaToGithub** [comment]
#### pro.mathias.lang (@Geod24) commented on 2020-02-19T05:26:08Z



````markdown
For C `pragma(mangle)` is an easy workaround, however for `extern(C++)`, not only is the mangling non-trivial, but it's currently impossible to do for anything templated, since the mangling depend on template parameters which are not available to `pragma(mangle)`.
````

**Comment by dlangBugzillaToGithub** [comment]
#### tim.dlang commented on 2024-06-01T14:24:09Z




Using `pragma(mangle)` is also annoying for type names, because every function using the renamed type needs to use the changed mangling. This is for example necessary for `std::function`, because `function` is a keyword in D. It would be nice if you could change the mangled name of a type once and every function using the type gets the changed name automatically. It could look something like this:
```d
import core.stdcpp.xutility : StdNamespace;
import std.traits;

extern(C++, (StdNamespace)) extern(C++, class)
pragma(mangle_name, "function") // This type is called function in C++
struct std_function(F)
{
    // ...
}

extern(C++) void f(ref const std_function!(FunctionTypeOf!(void function())) callback);
```

Currently every function like `f` using `std_function` would need `pragma(mangle)` and the exact mangling depends on operating system and processor architecture. It is possible to generate the correct mangling using CTFE, but this still needs to be done for every function.

**Comment by thewilsonator** [comment]
binding to `std;:function` is possible now.

**Comment by tim-dlang** [comment]
> binding to `std;:function` is possible now.

How is this possible without `pragma(mangle)` for every usage?

**Comment by thewilsonator** [comment]
https://github.com/dlang/dmd/blob/master/compiler/test/compilable/issue21203.d#L124-L140

**Comment by tim-dlang** [comment]
Thanks, that works.
