### ISSUE TITLE
Questions about the release of the DMD version

### ISSUE THREAD

**Issue by fenginsc** [dlang/dmd#20571]
I see this(`https://dlang.org/changelog/release-schedule.html`) release schedule, why hasn't version 2.110 been released yet what happened? It should be released in August according to the plan.

**Comment by ntrel** [comment]
See https://forum.dlang.org/post/xlsnoajvuphefxlestwu@forum.dlang.org

**Comment by fenginsc** [comment]
> See https://forum.dlang.org/post/xlsnoajvuphefxlestwu@forum.dlang.org

thanks!
