### ISSUE TITLE
hasIndirections does not handle static arrays of length 0 correctly

### ISSUE THREAD

**Issue by jmdavis** [dlang/dmd#20601]
This code fails to compile

```
    import std.traits;
    static assert(!hasIndirections!(int*[0]));
```

The static array doesn't actually have any elements, so it doesn't have any indirections (much as it would if it did have elements), but the current implementation treats it like it does. Looking at the implementation in core.internal.traits, the implementation tries to treat static arrays of length 0 as having no indirections, but it's missing parens in a key place, and there is no test to catch that case, so it currently gives the wrong answer.

**Comment by thewilsonator** [comment]
This sounds like a phobos issue

**Comment by jmdavis** [comment]
> This sounds like a phobos issue, not a dmd/druntime

It is a druntime issue, because the implementation for `hasIndirections` is in core.internal.traits, which the std.traits one then uses.
