### ISSUE TITLE
aliasing for fields does not work

### ISSUE THREAD

**Issue by WalterBright** [dlang/dmd#20610]
```
struct T {
    int k,i = 2;
}

struct S {
    int x;
    T t;
    alias ti = t.i;
}

int main() {
    T t = T(1, 2);
    S s;
    assert(s.ti == 2); // Error: accessing non-static variable `i` requires an instance of `T`
    return 0;
}
```
`s.ti` should be equivalent to `s.t.i`

**Comment by WalterBright** [comment]
fix: https://github.com/dlang/dmd/pull/20611

**Comment by TurkeyMan** [comment]
Wonderful!

Will this also address elements of an `AliasSeq`?
```d
alias seq = AliasSeq!(x, y, z);
alias x = seq[0];
```

**Comment by WalterBright** [comment]
Unfortunately, not. Wanna submit a bug report?

**Comment by TurkeyMan** [comment]
In general, I think it might be really useful to make `alias` work generally with expressions.
Since I think the reason that `alias x = seq[0]` doesn't work, is because it is effectively aliasing a `[]` operator expression? There are so many situations that fall into this general category where alias fails; is it out of the question for alias to be able to carry an expression?

**Comment by TurkeyMan** [comment]
> Unfortunately, not. Wanna submit a bug report?

https://github.com/dlang/dmd/issues/20612

**Comment by WalterBright** [comment]
Ehhxcellent!

**Comment by WalterBright** [comment]
There are already ambiguities that I struggled to account for in fixing this issue. More aliasing means more trouble with this. Aliasing tries to do too much!

Aliasing an expression is better done with a lambda, where it is well defined. The lambda will get inlined, and all will be well.

ImportC creates lambdas out of macros that look like expressions. This works quite well.

**Comment by TurkeyMan** [comment]
Aliases are more often used to refer to types or symbols... In the cases of interest if a lambda was workable, there wouldn't be anything to talk about.
